from collections.abc import Iterable
from typing import Protocol

from src.core.types.category_diff import CategoryDiff
from src.shared.types.category_id_pair import CategoryIdPair


class CategoryDiffRepository(Protocol):
    def all(self) -> Iterable[tuple[CategoryIdPair, CategoryDiff]]: ...
    def all_titles(self) -> Iterable[str]: ...
    def get(self, pair: CategoryIdPair) -> CategoryDiff | None: ...
    def add(self, pair: CategoryIdPair, diff_text: CategoryDiff) -> None: ...
