from typing import Protocol, Optional

from src.core.domain.category import Category


class CategoryRepository(Protocol):
    def get_all(self) -> list[Category]: ...
    def get_titles_str(self) -> str: ...
    def get_all_with_kw(self, method: Optional[str] = None) -> str: ...
    def get_all_with_bw(self) -> str: ...
    def get_all_with_tfidf(self) -> str: ...
    def get_by_titles(self, titles_list: list[str]) -> list[Category]: ...
