[tool.black]
line-length = 121
target-version = ['py312']

[tool.isort]
profile = "black"
line_length = 121

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
warn_return_any = false
check_untyped_defs = true

[tool.ruff]
line-length = 121
target-version = "py312"
fix = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "D100",    # не требовать docstring у модуля
  "D101",
  "D102",
  "D103",    # не требовать docstring у функций (часто мешает в Typer-командах)
  "D104",    # не требовать docstring у __init__.py
  "D107",
  "PLR0913", # не ругаться на слишком много аргументов (Typer-команды)
  "RUF001",  # не ругаться на русские буквы, похожие на латинские (например, с vs c)
  "ERA001",  #  ERA001 Found commented-out code
  "T201",  # print command
  "D400",
  "D205",
  "D415",
  "BLE001"
]
