from typing import Protocol, Iterable, Optional

from core.types.category_diff import CategoryDiff
from shared.types.category_id_pair import CategoryIdPair


class CategoryDiffRepository(Protocol):
    def all(self) -> Iterable[tuple[CategoryIdPair, CategoryDiff]]: ...
    def all_titles(self) -> Iterable[str]: ...
    def get(self, pair: CategoryIdPair) -> Optional[CategoryDiff]: ...
    def add(self, pair: CategoryIdPair, diff_text: CategoryDiff) -> None: ...
